development:
#  host: localhost
#  database: wheel_development
  host: staff.mongohq.com
  port: 10054
  username: root
  password: MongoDbPassWord
  database: nwn_production



test:
  host: localhost
  database: wheel_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
